#!/bin/bash

DFLAG=
BINEXT=

if [ "$1" == "" ]; then
  echo usage: $0 [-p] source.grass
  exit 1
fi

if [ "$1" == "-p" ]; then
  DFLAG="$DFLAG -debug"
  shift
fi

OUTPUTBIN=${1%.*}$BINEXT
DSRCDIR=$(cd $(dirname $0); pwd)

cp -f $1 $DSRCDIR/source.grass
dmd $DFLAG -J$DSRCDIR -of$OUTPUTBIN $DSRCDIR/grassctc.d

